# Welcome to Jekyll!
#
# This config file is meant to be read by Jekyll, but also by the Clean Blog theme.
# It contains some non-standard Jekyll configuration to help with SEO, while maintaining
# Jekyll compatibility.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Talking tech with Mark
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Exploring the latest developments in artificial intelligence, big tech, and emerging technologies. 
  Deep dives into AI breakthroughs, tech industry analysis, and future trends.
baseurl: "/myblog/" # the subpath of your site, e.g. /blog
url: "https://markekvall.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  markekvall

# Build settings
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

# Clean Blog theme configuration
clean_blog:
  # Meta
  meta:
    title: "AI & Tech Insights - Mark Ekvall's Blog"
    description: "Exploring AI, big tech, and emerging technologies"
    keywords: "AI, artificial intelligence, big tech, technology, machine learning, emerging tech"
  
  # Header
  header:
    title: "AI & Tech Insights"
    subtitle: "Exploring the future of technology"
    background: "img/home-bg.jpg"
  
  # Footer
  footer:
    description: "Mark Ekvall's thoughts on AI, big tech, and emerging technologies"
    social:
      - name: "GitHub"
        url: "https://github.com/markekvall"
        icon: "fab fa-github"
      - name: "Twitter"
        url: "https://twitter.com/jekyllrb"
        icon: "fab fa-twitter"
  
  # Navigation
  navigation:
    - name: "Home"
      url: "/"
    - name: "About"
      url: "/about/"
    - name: "Posts"
      url: "/posts/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
